server:
  port: 9033
  servlet:
    context-path: /gateway

spring:
  cloud:
    gateway:
      discovery:
        locator:
          #开启注册中心路由功能
          enabled: true
      routes:
        #路由ID，要保证唯一，建议配合服务名
        - id: serviceSmep
        ##uri: http://localhost:9028/ #服务提供方的地址
        ##uri: ws://localhost:9028/ #websocket的方式
          uri:  http://127.0.0.1:9530/smep/
          #断言
          predicates:
            - Path=/gateway/api-smep/**

